env:
    # Cirrus Specific Var (Do *NOT* Change) ok
    CIRRUS_SHELL: bash

task:
  name: "Build"
  timeout_in: 180m
  container:
      image: ghcr.io/catthehacker/ubuntu:act-latest
      cpu: 8
      memory: 32G

  Sync_script:
      - sudo apt update && curl -sL https://raw.githubusercontent.com/SA-17/cr1/main/b.sh | bash
